# Generated by Django 3.2.16 on 2023-01-13 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together={('owner', 'post')},
        ),
    ]
