# Generated by Django 3.2.16 on 2023-01-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
